### ISSUE TITLE
DoLeakyBucketWait Issue when checkResult.RuleCheckResults.Count() == 0 , if I add some filter or Middleware

### ISSUE THREAD

**Issue by gang89liu** [bosima/FireflySoft.RateLimit#1]
private static async Task DoLeakyBucketWait(AlgorithmCheckResult checkResult)
        {
            if (checkResult.RuleCheckResults.Count() == 0)
                return;
            // Simulation leaky bucket algorithm queuing mechanism
            var wait = checkResult.RuleCheckResults.Max(d => d.Wait);
            if (wait > 0)
            {
                await Task.Delay((int)wait).ConfigureAwait(false);
            }
        }

**Comment by bosima** [comment]
Sorry, I could not reproduce this problem, please provide your full test code

**Comment by gang89liu** [comment]
上面那哥子，应该跟我报的一样的异常，就是调用的不是异步的方法来确定规则ExtractTarget， CheckRuleMatching，然后var wait = checkResult.RuleCheckResults.Max(d => d.Wait);这句就要报错。我调试的时候发现的，然后我就在前面加了这句
if (checkResult.RuleCheckResults.Count() == 0)
return;

**Comment by gang89liu** [comment]
我的启用限流是放在权限后的，因为我这边要获取用户相关的信息
            app.UseRouting();
            app.UseCors("AllowDomain");

            app.UseAuthentication();
            app.UseAuthorization();

            if(RateLimitConfig.Config?.Enable == true)
            {
                app.UseRateLimit();
            }

**Comment by bosima** [comment]
已经增加判断，请拉取最新配置。

**Comment by gang89liu** [comment]
好的，谢谢
