### ISSUE TITLE
同一个程序是否支持多个限流算法

### ISSUE THREAD

**Issue by chrcao** [bosima/FireflySoft.RateLimit#13]
期望使用固定窗口算法来控制ip某个时间端不要超过特定数量
期望使用令牌桶算法来控制访问的限流
有什么方法可以同时注册使用这两种算法吗？

**Comment by bosima** [comment]
这个需要自己做个中间件，或者加个过滤器，直接应用算法，而不用我发布的 asp.net core中间件。

参考示例中的 Others：
[https://github.com/bosima/FireflySoft.RateLimit#others](https://github.com/bosima/FireflySoft.RateLimit#others)

创建两个全局的算法实例，然后在请求中依次调用两个算法的 Check 方法。

**Comment by chrcao** [comment]
谢谢，我按照这个思路实现了一个

**Comment by chrcao** [comment]
这个插件为什么不再丰富下功能，挺好的。

**Comment by bosima** [comment]
> 这个插件为什么不再丰富下功能，挺好的。

一是时间不多，二是怕复杂了会变成四不像，所以只关注了最核心的算法部分。

谢谢你的认可和建议。
