### ISSUE TITLE
FireflySoft.RateLimit.AspNetCore.Sample  project startup fail

### ISSUE THREAD

**Issue by heartFireTree** [bosima/FireflySoft.RateLimit#2]
![image](https://user-images.githubusercontent.com/32155877/120593193-b6135180-c471-11eb-9f0a-a2d8a07798cf.png)

be cause AddRateLimit inner  
 builder.AddSingleton<HttpInvokeInterceptor>(interceptor);
interceptor Default value cannot be null

**Comment by bosima** [comment]
It has been solved. Please pull the latest code.
