### ISSUE TITLE
CheckRuleMatching return false Will it take effect

### ISSUE THREAD

**Issue by heartFireTree** [bosima/FireflySoft.RateLimit#3]
还有个问题，就是实例化限流规则类的 自定义CheckRuleMatching 委托规则 如果返回false，是不是应该就是不对改规则进行限流，可是实际上貌似没什么作用，甚至还抛出一个异常
![image](https://user-images.githubusercontent.com/32155877/120954575-0e07cc00-c782-11eb-87a3-d07617f75ac3.png)

**Comment by heartFireTree** [comment]
![image](https://user-images.githubusercontent.com/32155877/120953698-237bf680-c780-11eb-8bd9-cd062c72af0a.png)
这一行，圈红线的地方是我自己加的，不然程序会报错

**Comment by bosima** [comment]
`if (checkResult.RuleCheckResults.Any())
                {
                    await DoLeakyBucketWait(checkResult).ConfigureAwait(false);
                }`

已经增加判断，请拉取最新代码。
