### ISSUE TITLE
Dynamically change the flow limiting rule configuration at program runtime

### ISSUE THREAD

**Issue by heartFireTree** [bosima/FireflySoft.RateLimit#4]
我看Sample项目都是直接在服务里面注入的，如何支持在程序运行时动态更改限流算法的参数和配置呢

**Comment by bosima** [comment]
You can call  IAlgorithm.UpdateRules or UpdateRulesAsync.

**Comment by heartFireTree** [comment]
> You can call IAlgorithm.UpdateRules or UpdateRulesAsync.

Can you give me a complete example in the AspNetCore.Sample project?

**Comment by bosima** [comment]
You can refer to this unit test: [BaseAlgorithmTest.cs](https://github.com/bosima/FireflySoft.RateLimit/blob/master/FireflySoft.RateLimit.Core.UnitTest/BaseAlgorithmTest.cs)

**Comment by heartFireTree** [comment]
> You can refer to this unit test: [BaseAlgorithmTest.cs](https://github.com/bosima/FireflySoft.RateLimit/blob/master/FireflySoft.RateLimit.Core.UnitTest/BaseAlgorithmTest.cs)

![image](https://user-images.githubusercontent.com/32155877/121502911-2b9f9480-ca13-11eb-9e51-174dc40299a3.png)

如果我的验证规则需要从数据库里面获取相应数据，岂不是在每次请求的时候 这里面有多少个list就要遍历执行多少次

就是我想把每一个单独的api地址分别配置单独的令牌桶和加入量等参数，然后将一系列参数存放到数据库，然后通过数据库的值直接同步到限流规则

just like [AspNetCoreRateLimit](https://github.com/stefanprodan/AspNetCoreRateLimit/issues/212)  configuration pattern. But I need your TokenBucketAlgorithm，Because your algorithm support is richer and more powerful than AspNetCoreRateLimit

**Comment by bosima** [comment]
目前没有这个的开发计划，需要用户自己实现规则的更新，比如：通过一个定时器，检查内存与数据库中的配置；或者提供一个endpoint，y

**Comment by bosima** [comment]
由于目前只关注于核心的算法和限流处理，对于外围的实现还比较简单，未来会做一些增强，但时间无法保证。

目前这块需要自己实现一个配置解析程序，将对人更友好的配置转换为RateLimitRule。

如果担心数据库查询性能问题，这里可以做一个内存缓存。

关于更便捷的更新方式，目前没有开发计划，需要自己实现规则的更新，比如：
1、通过一个定时器，检查内存与数据库中的配置。
2、提供一个endpoint，配置变化时，由别的程序来调用这个接口。
