### ISSUE TITLE
Redis storage have a defect

### ISSUE THREAD

**Issue by heartFireTree** [bosima/FireflySoft.RateLimit#5]
![image](https://user-images.githubusercontent.com/32155877/121674967-522e0000-cae5-11eb-9828-f386f2a26528.png)

这是令牌桶算法方式在redis的存储，这个key的剩余令牌桶数量不会自动更新，只有当每次程序访问的时候才能去更新key剩余的容量还有多少，this one of tow defect,

每次新的请求都会重新创建一个Key，而且这个key不会自动过期，也就是说随着程序运行的越来越久，访问量越来越高，那么redis的key也会越来越多，只能去手动维护？

**Comment by bosima** [comment]
Repeated issue
