### ISSUE TITLE
Defects of redis storage

### ISSUE THREAD

**Issue by heartFireTree** [bosima/FireflySoft.RateLimit#6]
![image](https://user-images.githubusercontent.com/32155877/121674967-522e0000-cae5-11eb-9828-f386f2a26528.png)

这是令牌桶算法方式在redis的存储，这个key的剩余令牌桶数量不会自动更新，只有当每次程序访问的时候才能去更新key剩余的容量还有多少，this one of tow defect,

每次新的请求都会重新创建一个Key，而且这个key不会自动过期，也就是说随着程序运行的越来越久，访问量越来越高，那么redis的key也会越来越多，只能去手动维护？

**Comment by bosima** [comment]
1、令牌桶中的令牌数会在每次访问的时候进行计算处理，计算出当前令牌中应该有几个令牌，这样避免了创建Timer或者线程去维护令牌桶。设计确实如此。这对于实际使用会有什么问题吗？

**Comment by bosima** [comment]
1、令牌桶中的令牌数会在每次访问的时候进行计算处理，计算出当前令牌中应该有几个令牌，这样避免了创建Timer或者线程去维护令牌桶。设计确实如此。这对于实际使用会有什么问题吗？

**Comment by bosima** [comment]
1、令牌桶中的令牌数会在每次访问的时候进行计算处理，计算出当前令牌中应该有几个令牌，这样避免了创建Timer或者线程去维护令牌桶。设计确实如此。这对于实际使用会有什么问题吗？

2、这个问题需要解决，可能提供一个配置参数，欢迎提出方案。

**Comment by bosima** [comment]
对于第2个问题，如果Redis中会处理很多个服务的限流，并且接口是经常变化的，则需要解决key的释放问题，否则意义不大。
解决方法也很简单，在计数时同时设置过期时间，过期时间要超过令牌桶被填满的时间。

`redis.call('set',KEYS[1],bucket_amount,'PX',expire_time+100)`

` redis.call('set',st_key,start_time,'PX',expire_time)`

相比mset的方法，吞吐量上会有细微的损失。

我已经提交这个修改，但是还没决定以后的版本中如何处理这个问题，因为ROI。

**Comment by heartFireTree** [comment]
> 对于第2个问题，如果Redis中会处理很多个服务的限流，并且接口是经常变化的，则需要解决key的释放问题，否则意义不大。
> 解决方法也很简单，在计数时同时设置过期时间，过期时间要超过令牌桶被填满的时间。
> 
> `redis.call('set',KEYS[1],bucket_amount,'PX',expire_time+100)`
> 
> ` redis.call('set',st_key,start_time,'PX',expire_time)`
> 
> 相比mset的方法，吞吐量上会有细微的损失。
> 
> 我已经提交这个修改，但是还没决定以后的版本中如何处理这个问题，因为ROI。

cool，Successfully solved the problem of manual maintenance
