### ISSUE TITLE
LeakyBucket bug when the first period has over outflow_quantity_per_unit quantity let in bucket

### ISSUE THREAD

**Issue by mofee** [bosima/FireflySoft.RateLimit#8]
asume that the bucket
 capacity : 20
 outflow_unit: 500 ms
 outflow_quantity_per_unit: 5
 amount: 1

in the first period ( the first outflow unit: the first 500ms), has 25 requests,  end of the period, 5 requests pass, and 20 requests in the buecket.
in the second period, in the theory, also has 5 requests pass (wait is 0, ret = [0, x, 0]),  but actually, in the second period all request all return wait > 0

that is: when capacity >= outflow_quantity_per_unit * n (n >= 2), and the first period let in the bucket quantity greater than  outflow_quantity_per_unit , then cause the problem.
because the below sentence:
if(current_value>outflow_quantity_per_unit)

**Comment by mofee** [comment]
RedisLeakyBucketAlgorithm

**Comment by bosima** [comment]
There may be some misunderstandings here. 
Please review the unit test below:

`
public void TestFirstPeriodOverflow()
{

    // capacity: 20
    // outflow_unit: 500ms
    // outflow_quantity_per_unit: 5
    // amount: 1

    var processor = GetAlgorithm(20, 5, TimeSpan.FromMilliseconds(500), 0);

    for (int i = 1; i <= 30; i++)
    {
        // take to the second period after 25th request
        if (i == 26)
        {
            Thread.Sleep(500);
        }

        var checkResult = processor.Check(new SimulationRequest()
        {
            RequestId = Guid.NewGuid().ToString(),
            RequestResource = "home",
            Parameters = new Dictionary<string, string>() {
                        { "from","sample" },
                }
        });

        // the last request of the first period
        if (i == 25)
        {
            Assert.AreEqual(20, checkResult.RuleCheckResults.First().Count);
            Assert.IsTrue(checkResult.RuleCheckResults.First().Wait > 1900);
        }

        // the first request of the second period
        if (i == 26)
        {
            // first, five requests flow out of the leaky bucket, 
            // then, one request is added to the leaky bucket.
            // the current number of requests in the leaky bucket is: 16 = 20 - 5 + 1, 
            // and this request will be processed after the last 15th requests,
            // so the current request must wait, and all requests in the second period must wait
            Assert.AreEqual(16, checkResult.RuleCheckResults.First().Count);
            Assert.IsTrue(checkResult.RuleCheckResults.First().Wait > 1900);
        }
    }
}`

[view all unit test code](https://github.com/bosima/FireflySoft.RateLimit/blob/master/FireflySoft.RateLimit.Core.Test/RedisLeakyBucketAlgorithmTest.cs)

**Comment by mofee** [comment]
thanks, it means these ret=[0, x, n] (n > 0) results will sleep in client app, and after the sleep will pass by not communicate with redis.
