### ISSUE TITLE
FixedWindowRule可以支持动态往容器内增加可用数量么？

### ISSUE THREAD

**Issue by One-One-Code** [bosima/FireflySoft.RateLimit#9]
您好，

我有这样的一个场景，控制10分钟内只能有1000个用户进入系统，在这期间如果进入的用户有退出的话，我想递增可进入人数

假设：
StatWindow=TimeSpan.FromSeconds(10*60),
LimitNumber=1000,

一分钟之后，剩余可以登录的用户数为800，此时有10个用户退出

我想把当前剩余可以登录的用户数置为810

请问这种在程序运行过程中修改剩余数量的场景支持吗？或者说未来打算支持么？

**Comment by bosima** [comment]
FireflySoft.RateLimit 目前都是基于时间窗口进行流量控制的，你的需求是要增加一个控制逻辑，目前并不能很好的适配，但是有一个方法：

因为规则是可以在运行时更新的，如果有用户退出，你可以通过修改规则，增加限流阈值，来允许相应数量的用户登录。
比如有1个用户退出，就修改下限流规则：LimitNumber+=1，然后通过UpdateRules更新规则。
不过更新LimitNumber的值不是原子操作，你可能需要自己想办法保证多线程下LimitNumber的值不会出现问题。

**Comment by bosima** [comment]
可能增加一种算法才能更好的解决此类问题，放在这个类库中是否具有意义，之前并没考虑过，还需思考。

**Comment by One-One-Code** [comment]
是的，我也是找不到更合适的，才打算用FixedWindowRule来变相解决我的问题，我不想更新规则的LimitNumber，只是想更新current的值，框架不支持的话我再想想其他办法
![image](https://user-images.githubusercontent.com/44698989/160057910-f29373a3-93a4-4ad3-bc59-eade1b364c96.png)

**Comment by bosima** [comment]
不是本库要支持的功能。
